### ISSUE TITLE
Compiling guide.

### ISSUE THREAD

**Issue by ftk789** [jariz/StarTruckerCustomRadio#1]
Right now I want to add a feature to the mod where it would be Twitch Integrated. But I have an issue compiling.

I'm trying to make it so it loads new sound files from folder after the current song ends. But would get such erros like this:

![image](https://github.com/user-attachments/assets/e0f7ae79-0f19-4655-a4d3-fc69539135a7)

would you be kind to help/guide me/us on how to compile this mod ourselves?

Thank you in advance!

**Comment by jariz** [comment]
Hi @ftk789! Are all required assemblies added to the project?  
You might have to manually add them because it's probably pointing to the path where it's located on my pc.  

See: https://melonwiki.xyz/#/modders/quickstart?id=assembly-references  
The game is a il2cpp game.

**Comment by ftk789** [comment]
Thank you so much for your response. I gladly figured it out with your link. I just missed all the DLL references and had to re-direct them into the right path

Thank you very much.
